[project]
name = "pyenv-manager-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=2.1.1",
]

[project.scripts]
pyenv-manager-mcp = "pyenv_manager_mcp:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
